name: CI/CD Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v2

    - name: Se connecter à Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construire et pousser l'image Docker
      run: |
        docker build -t monrepo/service-paiement:${{ github.sha }} .
        docker tag monrepo/service-paiement:${{ github.sha }} monrepo/service-paiement:latest
        docker push monrepo/service-paiement:${{ github.sha }}
        docker push monrepo/service-paiement:latest

    - name: Mettre à jour Kubernetes
      run: |
        kubectl set image deployment/service-paiement paiement-container=monrepo/service-paiement:${{ github.sha }}
